-- noinspection SqlNoDataSourceInspectionForFile

CREATE TABLE VENUE
(
    ID                                   INTEGER NOT NULL,
    CAPACITY                             INTEGER NOT NULL,
    CITY                                 CHARACTER VARYING(255),
    DISTANCE_FROM_PUBLIC_TRANSPORT_IN_KM INTEGER NOT NULL,
    FOOD_PROVIDED                        BOOLEAN NOT NULL,
    FREE_PARKING_AVAILABLE               BOOLEAN NOT NULL,
    INDOOR                               BOOLEAN NOT NULL,
    LINK_MORE_INFO                       CHARACTER VARYING(255),
    OUTDOOR                              BOOLEAN NOT NULL,
    VENUE_NAME                           CHARACTER VARYING(255)
);
ALTER TABLE VENUE
    ADD CONSTRAINT CONSTRAINT_4D PRIMARY KEY (ID);


CREATE TABLE ARTIST
(
    ID             INTEGER NOT NULL,
    ARTIST_NAME    CHARACTER VARYING(255),
    BIO            CHARACTER VARYING(500),
    GENRE          CHARACTER VARYING(255),
    LINK_MORE_INFO CHARACTER VARYING(255),
    PORTFOLIO      CHARACTER VARYING(255)

);
ALTER TABLE ARTIST
    ADD CONSTRAINT CONSTRAINT_73 PRIMARY KEY (ID);


CREATE TABLE PARTY
(
    id                   INT GENERATED ALWAYS AS IDENTITY,
    DATE                 DATE    NOT NULL,
    DOORS                TIME    NOT NULL,
    EXTRA_INFO           CHARACTER VARYING(255),
    NAME                 CHARACTER VARYING(255),
    PRICE_IN_EUR         INTEGER,
    PRICE_PRESALE_IN_EUR INTEGER,
    VENUE_ID             INTEGER NOT NULL
);
ALTER TABLE PARTY
    ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID);
ALTER TABLE PARTY
    ADD CONSTRAINT FKSU674HM226PIJ7JQM917FFTGU FOREIGN KEY (VENUE_ID) REFERENCES VENUE (ID);

CREATE TABLE PARTY_ARTISTS
(
    PARTIES_ID INTEGER NOT NULL,
    ARTISTS_ID INTEGER NOT NULL
);
ALTER TABLE PARTY_ARTISTS
    ADD CONSTRAINT FKBXNPEY26NWY4RQGBMBECBPRKD FOREIGN KEY (PARTIES_ID) REFERENCES PARTY (ID);
ALTER TABLE PARTY_ARTISTS
    ADD CONSTRAINT FK5PY1NEAW2AEQ1ISBB3YJAI3Q0 FOREIGN KEY (ARTISTS_ID) REFERENCES ARTIST (ID);


CREATE TABLE ANIMAL
(
    id       INT GENERATED ALWAYS AS IDENTITY,
    BIO      CHARACTER VARYING(255),
    CITY     CHARACTER VARYING(255),
    NAME     CHARACTER VARYING(255),
    USERNAME CHARACTER VARYING(255)

);
ALTER TABLE ANIMAL
    ADD CONSTRAINT CONSTRAINT_7 PRIMARY KEY (ID);

CREATE TABLE ANIMAL_PARTIES
(
    ANIMALS_ID INTEGER NOT NULL,
    PARTIES_ID INTEGER NOT NULL
);
ALTER TABLE ANIMAL_PARTIES
    ADD CONSTRAINT FK5VL0139J0WI6BMMAD3HPPGRE7 FOREIGN KEY (PARTIES_ID) REFERENCES PARTY (ID);
ALTER TABLE ANIMAL_PARTIES
    ADD CONSTRAINT FKJ3Y4UYK6GR2VV2W9GUI3N1A6K FOREIGN KEY (ANIMALS_ID) REFERENCES ANIMAL (ID);

